In [1]:
import numpy as np
import cv2
import pandas as pd
import glob

In [2]:
andesite_data = []
files = glob.glob ("C:/Users/KIIT/Downloads/geological_similarity/andesite/*.jpg")
for myFile in files:
    image = cv2.imread (myFile)
    andesite_data.append (image)

print('Andesite_data shape:', np.array(andesite_data).shape)

Andesite_data shape: (5000, 28, 28, 3)

In [3]:
gneiss_data = []
files = glob.glob ("C:/Users/KIIT/Downloads/geological_similarity/gneiss/*.jpg")
for myFile in files:
    image = cv2.imread (myFile)
    gneiss_data.append (image)

print('gneiss_data shape:', np.array(gneiss_data).shape)

gneiss_data shape: (5000, 28, 28, 3)

In [4]:
marble_data = []
files = glob.glob ("C:/Users/KIIT/Downloads/geological_similarity/marble/*.jpg")
for myFile in files:
    image = cv2.imread (myFile)
    marble_data.append (image)

print('marble_data shape:', np.array(marble_data).shape)

marble_data shape: (4998, 28, 28, 3)

In [5]:
quartzite_data = []
files = glob.glob ("C:/Users/KIIT/Downloads/geological_similarity/quartzite/*.jpg")
for myFile in files:
    image = cv2.imread (myFile)
    quartzite_data.append (image)

print('marble_data shape:', np.array(quartzite_data).shape)

marble_data shape: (5000, 28, 28, 3)

In [6]:
rhyolite_data = []
files = glob.glob ("C:/Users/KIIT/Downloads/geological_similarity/rhyolite/*.jpg")
for myFile in files:
    image = cv2.imread (myFile)
    rhyolite_data.append (image)

print('rhyolite_data shape:', np.array(rhyolite_data).shape)

rhyolite_data shape: (5000, 28, 28, 3)

In [7]:
schist_data = []
files = glob.glob ("C:/Users/KIIT/Downloads/geological_similarity/schist/*.jpg")
for myFile in files:
    image = cv2.imread (myFile)
    schist_data.append (image)

print('schist_data shape:', np.array(schist_data).shape)

schist_data shape: (5000, 28, 28, 3)

In [8]:
df1 = pd.DataFrame(columns=list(range(2352)))
for i in range(len(schist_data)):
         df1.loc[i]=schist_data[i].flatten()

In [9]:
df2 = pd.DataFrame(columns=list(range(2352)))
for i in range(len(rhyolite_data)):
         df2.loc[i]=rhyolite_data[i].flatten()

In [10]:
df3 = pd.DataFrame(columns=list(range(2352)))
for i in range(len(quartzite_data)):
         df3.loc[i]=quartzite_data[i].flatten()

In [11]:
df4 = pd.DataFrame(columns=list(range(2352)))
for i in range(len(marble_data)):
         df4.loc[i]=marble_data[i].flatten()

In [12]:
df5 = pd.DataFrame(columns=list(range(2352)))
for i in range(len(gneiss_data)):
         df5.loc[i]=gneiss_data[i].flatten()

In [13]:
df6 = pd.DataFrame(columns=list(range(2352)))
for i in range(len(andesite_data)):
         df6.loc[i]=andesite_data[i].flatten()

In [14]:
schist = []
for i in range(5000):
    schist.append('Schist')
df1['Type'] = schist

In [15]:
rhyolite = []
for i in range(5000):
    rhyolite.append('Rhyolite')
df2['Type'] = rhyolite

In [16]:
quartzite = []
for i in range(5000):
    quartzite.append('Quartzite')
df3['Type'] = quartzite

In [17]:
marble = []
for i in range(4998):
    marble.append('Marble')
df4['Type'] = marble

In [18]:
gneiss = []
for i in range(5000):
    gneiss.append('Gneiss')
df5['Type'] = gneiss

In [19]:
andesite = []
for i in range(5000):
    andesite.append('Andesite')
df6['Type'] = andesite

In [20]:
frames = [df1, df2, df3,df4,df5,df6]

df_final = pd.concat(frames)

In [21]:
df_final = df_final.reset_index(inplace = True)

In [22]:
df_final.to_csv(r'Geological Image Similarity1.csv',index = False)

In [23]:
df= pd.read_csv('Geological Image Similarity1.csv')

In [24]:
df.drop(['index'],axis=1)

,0,1,2,3,4,5,6,7,8,9,...,2343,2344,2345,2346,2347,2348,2349,2350,2351,Type
0,159,153,146,147,149,137,120,137,116,97,...,61,65,89,91,91,103,100,101,105,Schist
1,137,129,166,165,161,186,176,180,181,173,...,170,175,166,166,166,166,166,165,167,Schist
2,215,216,212,216,215,211,220,212,212,214,...,211,210,206,203,201,200,207,205,205,Schist
3,180,181,172,148,150,138,151,159,136,166,...,185,189,177,187,190,175,185,188,173,Schist
4,86,102,114,74,90,102,84,100,116,102,...,175,181,162,170,171,161,167,168,159,Schist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29993,59,70,50,71,82,62,68,77,56,64,...,77,76,56,84,80,61,96,92,73,Andesite
29994,119,116,102,118,115,101,125,121,110,109,...,143,137,118,156,152,128,153,149,124,Andesite
29995,114,122,99,119,127,104,116,125,99,137,...,125,127,107,108,110,91,117,119,100,Andesite
29996,133,132,118,138,137,123,139,136,121,138,...,124,117,100,134,126,109,133,125,108,Andesite
29997,170,148,137,145,125,114,137,116,108,144,...,224,203,195,217,195,184,204,182,171,Andesite

In [25]:
from sklearn.utils import shuffle
df = shuffle(df)

In [26]:
df

,index,0,1,2,3,4,5,6,7,8,...,2343,2344,2345,2346,2347,2348,2349,2350,2351,Type
24328,4330,228,231,229,230,233,231,228,230,230,...,137,126,166,221,217,228,241,242,238,Gneiss
21207,1209,207,208,198,204,205,195,209,207,199,...,192,192,176,193,192,178,192,191,177,Gneiss
3561,3561,176,184,153,183,190,163,170,173,157,...,180,181,172,187,188,178,187,188,178,Schist
8364,3364,82,76,71,79,73,68,76,71,68,...,97,95,95,85,81,86,120,119,123,Rhyolite
19256,4256,17,38,69,14,33,66,19,31,73,...,15,35,76,33,52,87,53,72,105,Marble
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28290,3292,118,110,97,83,75,68,64,58,63,...,121,105,98,123,104,97,121,102,94,Andesite
22442,2444,40,48,61,37,46,60,43,53,70,...,220,221,225,217,219,220,219,221,222,Gneiss
20525,527,193,185,178,202,195,186,214,207,198,...,223,224,222,224,225,223,224,225,223,Gneiss
6374,1374,62,70,63,78,86,79,59,69,63,...,73,78,79,43,46,50,63,66,70,Rhyolite
2008,2008,100,110,98,97,107,94,103,116,100,...,164,168,157,147,147,147,136,136,142,Schist

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X=df.drop(['Type','index'],axis=1)
Y = df['Type']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.33)

In [29]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [30]:
accuracy_list = []
for i in range(95,100):
    model = RandomForestClassifier(n_estimators=i)
    model.fit(X_train, Y_train)  #fit the model
    pred = model.predict(X_test)
    accuracy_list.append(accuracy_score(Y_test, pred))

In [31]:
accuracy_list

[0.935959595959596,
 0.9366666666666666,
 0.9378787878787879,
 0.9378787878787879,
 0.9372727272727273,
 0.937070707070707,
 0.938989898989899,
 0.9351515151515152,
 0.9376767676767677,
 0.9384848484848485]

# Dealing with Deep Learning

In [32]:
dl_data=np.concatenate((schist_data, rhyolite_data,quartzite_data,marble_data,gneiss_data,andesite_data), axis=0)

In [33]:
dl_data = np.array(dl_data)

### Labeling Data 1-schist , 2- rhyolite , 3-quartzite , 4-marble , 5-gneiss , 6-andesite

In [34]:
label_data = []

In [35]:
for i in range(5000):
    label_data.append(1)
for i in range(5000):
    label_data.append(2)
for i in range(5000):
    label_data.append(3)
for i in range(4998):
    label_data.append(4)
for i in range(5000):
    label_data.append(5)
for i in range(5000):
    label_data.append(6)

In [36]:
len(label_data)

29998

In [37]:
from tensorflow import keras

In [38]:
import random
c = list(zip(dl_data, label_data))

random.shuffle(c)

dl_data, label_data = zip(*c)
X_tr,X_te,Y_tr,Y_te = train_test_split(dl_data,label_data , test_size=0.33)

In [39]:
GeographicalModel = keras.Sequential([
                               keras.layers.Flatten(input_shape = (28,28,3)), # as we have seen our data is in 28,28,3
                               keras.layers.Dense(128,activation='relu'),
                               keras.layers.Dense(10,activation = 'softmax')
])
GeographicalModel.compile(optimizer = 'adam' , loss = 'sparse_categorical_crossentropy' , metrics = ['accuracy'])
GeographicalModel.fit(x=np.array(X_tr), y=np.array(Y_tr),epochs = 10)

Epoch 1/10
629/629 [==============================] - 3s 4ms/step - loss: 27.9162 - accuracy: 0.4769
Epoch 2/10
629/629 [==============================] - 3s 4ms/step - loss: 8.2967 - accuracy: 0.5716
Epoch 3/10
629/629 [==============================] - 3s 4ms/step - loss: 3.5382 - accuracy: 0.5941
Epoch 4/10
629/629 [==============================] - 2s 4ms/step - loss: 2.0544 - accuracy: 0.6209
Epoch 5/10
629/629 [==============================] - 3s 4ms/step - loss: 1.1745 - accuracy: 0.6589
Epoch 6/10
629/629 [==============================] - 3s 4ms/step - loss: 0.7608 - accuracy: 0.6810
Epoch 7/10
629/629 [==============================] - 2s 4ms/step - loss: 0.6954 - accuracy: 0.7049
Epoch 8/10
629/629 [==============================] - 2s 4ms/step - loss: 0.6568 - accuracy: 0.7142
Epoch 9/10
629/629 [==============================] - 3s 4ms/step - loss: 0.6169 - accuracy: 0.7402
Epoch 10/10
629/629 [==============================] - 3s 4ms/step - loss: 0.6113 - accuracy: 0.7434

In [40]:
y_pred = []
for i in range(len(X_te)):
    img = X_te[i]
    img = (np.expand_dims(img,0)) 
    result = GeographicalModel.predict(img) 
    correctResult = np.argmax(result)
    y_pred.append(correctResult)

In [41]:
y_pred

[1,
 1,
 3,
 5,
 3,
 2,
 3,
 3,
 5,
 4,
 6,
 1,
 3,
 5,
 3,
 5,
 4,
 3,
 5,
 4,
 4,
 6,
 4,
 5,
 4,
 4,
 4,
 2,
 6,
 3,
 5,
 1,
 6,
 6,
 6,
 4,
 6,
 1,
 6,
 4,
 6,
 5,
 3,
 1,
 1,
 2,
 5,
 5,
 2,
 3,
 4,
 5,
 5,
 5,
 3,
 4,
 3,
 2,
 4,
 5,
 2,
 3,
 5,
 2,
 3,
 4,
 4,
 5,
 6,
 6,
 4,
 6,
 5,
 4,
 2,
 5,
 6,
 6,
 1,
 3,
 4,
 5,
 3,
 5,
 6,
 2,
 5,
 4,
 3,
 6,
 3,
 5,
 5,
 3,
 5,
 2,
 4,
 3,
 2,
 4,
 3,
 3,
 2,
 1,
 1,
 2,
 5,
 6,
 2,
 3,
 5,
 4,
 1,
 3,
 5,
 1,
 6,
 5,
 3,
 2,
 3,
 3,
 2,
 5,
 1,
 4,
 4,
 5,
 5,
 1,
 4,
 5,
 4,
 4,
 2,
 5,
 3,
 2,
 6,
 4,
 4,
 3,
 6,
 2,
 6,
 3,
 4,
 4,
 1,
 2,
 5,
 3,
 6,
 4,
 3,
 1,
 6,
 4,
 4,
 3,
 3,
 5,
 6,
 5,
 5,
 3,
 3,
 4,
 3,
 6,
 4,
 1,
 2,
 4,
 4,
 1,
 4,
 2,
 5,
 6,
 6,
 3,
 5,
 6,
 2,
 3,
 3,
 6,
 3,
 1,
 4,
 6,
 4,
 5,
 5,
 5,
 4,
 5,
 1,
 1,
 1,
 6,
 5,
 3,
 4,
 5,
 6,
 5,
 5,
 2,
 5,
 2,
 5,
 2,
 6,
 4,
 1,
 3,
 3,
 2,
 3,
 4,
 3,
 4,
 6,
 4,
 1,
 5,
 5,
 5,
 1,
 5,
 3,
 6,
 5,
 5,
 3,
 4,
 4,
 6,
 3,
 3,
 2,
 1,
 5,
 4,
 6,
 2,
 4,
 5,
 4,
 5,
 3,
 6,
 5,
 5,
 4,
 4,
 1,
 4,
 4,
 6,
 3,
 6,
 1,
 5,
 1,
 2,
 4,
 4,
 4,
 4,
 5,
 4,
 6,
 1,
 3,
 4,
 1,
 5,
 6,
 4,
 6,
 3,
 1,
 6,
 2,
 3,
 5,
 5,
 3,
 3,
 2,
 5,
 4,
 2,
 1,
 5,
 1,
 5,
 2,
 1,
 2,
 3,
 6,
 4,
 6,
 6,
 3,
 5,
 5,
 3,
 5,
 5,
 6,
 2,
 5,
 3,
 6,
 5,
 5,
 6,
 4,
 2,
 5,
 4,
 4,
 3,
 5,
 3,
 4,
 2,
 5,
 5,
 2,
 4,
 4,
 4,
 5,
 6,
 2,
 3,
 2,
 5,
 4,
 1,
 2,
 5,
 3,
 1,
 5,
 2,
 1,
 4,
 6,
 1,
 5,
 3,
 4,
 5,
 3,
 5,
 1,
 1,
 4,
 6,
 6,
 4,
 6,
 4,
 2,
 5,
 4,
 3,
 6,
 3,
 3,
 4,
 6,
 4,
 5,
 2,
 2,
 6,
 2,
 2,
 5,
 6,
 4,
 3,
 3,
 1,
 3,
 6,
 6,
 6,
 4,
 5,
 6,
 3,
 2,
 2,
 2,
 2,
 6,
 3,
 4,
 2,
 4,
 5,
 3,
 4,
 4,
 2,
 6,
 5,
 5,
 1,
 5,
 3,
 3,
 1,
 6,
 1,
 5,
 5,
 5,
 1,
 5,
 6,
 3,
 3,
 5,
 4,
 1,
 4,
 2,
 6,
 2,
 1,
 5,
 5,
 5,
 5,
 5,
 5,
 2,
 5,
 2,
 2,
 2,
 5,
 3,
 4,
 2,
 5,
 6,
 5,
 3,
 5,
 6,
 3,
 4,
 5,
 4,
 3,
 1,
 1,
 6,
 2,
 5,
 6,
 4,
 6,
 3,
 6,
 3,
 2,
 5,
 3,
 2,
 3,
 2,
 5,
 3,
 1,
 5,
 1,
 4,
 6,
 5,
 5,
 6,
 6,
 2,
 2,
 5,
 3,
 2,
 1,
 4,
 5,
 3,
 4,
 4,
 1,
 5,
 6,
 2,
 1,
 5,
 2,
 6,
 3,
 6,
 6,
 5,
 5,
 4,
 3,
 1,
 5,
 6,
 2,
 3,
 4,
 2,
 5,
 4,
 1,
 1,
 2,
 4,
 5,
 5,
 2,
 6,
 1,
 3,
 5,
 1,
 2,
 5,
 4,
 1,
 5,
 1,
 5,
 2,
 6,
 5,
 5,
 5,
 4,
 3,
 5,
 5,
 3,
 4,
 5,
 6,
 4,
 3,
 5,
 5,
 1,
 3,
 3,
 6,
 2,
 4,
 1,
 4,
 5,
 6,
 2,
 6,
 3,
 3,
 5,
 6,
 6,
 3,
 5,
 4,
 4,
 3,
 2,
 2,
 2,
 4,
 2,
 6,
 5,
 5,
 4,
 4,
 4,
 6,
 3,
 5,
 3,
 1,
 5,
 5,
 2,
 3,
 4,
 5,
 6,
 6,
 2,
 5,
 3,
 5,
 2,
 4,
 4,
 5,
 3,
 5,
 2,
 3,
 1,
 4,
 6,
 2,
 5,
 5,
 3,
 1,
 5,
 5,
 6,
 1,
 3,
 2,
 5,
 5,
 5,
 5,
 5,
 6,
 4,
 5,
 4,
 3,
 3,
 3,
 2,
 5,
 4,
 3,
 2,
 2,
 1,
 5,
 2,
 2,
 4,
 5,
 1,
 2,
 2,
 2,
 3,
 5,
 6,
 5,
 1,
 6,
 1,
 5,
 4,
 6,
 5,
 2,
 6,
 6,
 1,
 4,
 1,
 5,
 6,
 5,
 3,
 4,
 4,
 2,
 2,
 4,
 6,
 4,
 3,
 5,
 4,
 6,
 5,
 6,
 5,
 5,
 5,
 2,
 1,
 2,
 6,
 1,
 5,
 3,
 3,
 3,
 2,
 1,
 5,
 5,
 1,
 3,
 6,
 5,
 5,
 4,
 3,
 5,
 1,
 4,
 6,
 3,
 3,
 2,
 3,
 4,
 3,
 1,
 4,
 4,
 4,
 6,
 5,
 1,
 3,
 4,
 6,
 1,
 5,
 3,
 2,
 2,
 3,
 3,
 3,
 4,
 6,
 3,
 6,
 4,
 3,
 3,
 5,
 2,
 4,
 3,
 6,
 3,
 3,
 6,
 4,
 6,
 4,
 3,
 1,
 1,
 4,
 4,
 2,
 6,
 3,
 6,
 2,
 1,
 2,
 2,
 6,
 5,
 3,
 5,
 6,
 1,
 6,
 1,
 6,
 4,
 3,
 4,
 1,
 3,
 5,
 5,
 4,
 5,
 6,
 5,
 5,
 2,
 2,
 6,
 3,
 6,
 4,
 2,
 2,
 5,
 1,
 5,
 5,
 3,
 3,
 3,
 5,
 6,
 3,
 6,
 2,
 2,
 5,
 4,
 1,
 1,
 5,
 6,
 4,
 2,
 6,
 4,
 2,
 6,
 2,
 4,
 1,
 1,
 2,
 2,
 1,
 3,
 1,
 3,
 4,
 6,
 5,
 6,
 3,
 6,
 5,
 2,
 6,
 3,
 6,
 4,
 6,
 5,
 5,
 4,
 4,
 6,
 3,
 1,
 6,
 5,
 4,
 3,
 2,
 5,
 6,
 4,
 4,
 4,
 6,
 5,
 1,
 2,
 1,
 4,
 4,
 5,
 6,
 6,
 4,
 4,
 5,
 6,
 2,
 4,
 3,
 2,
 5,
 6,
 4,
 6,
 1,
 5,
 4,
 3,
 4,
 4,
 1,
 5,
 5,
 6,
 4,
 3,
 6,
 4,
 5,
 3,
 1,
 6,
 5,
 4,
 2,
 4,
 1,
 4,
 4,
 6,
 2,
 5,
 2,
 2,
 1,
 2,
 6,
 6,
 6,
 4,
 5,
 6,
 1,
 5,
 1,
 4,
 3,
 5,
 3,
 5,
 5,
 4,
 1,
 2,
 3,
 3,
 5,
 3,
 3,
 2,
 1,
 4,
 5,
 1,
 2,
 5,
 2,
 2,
 6,
 5,
 5,
 6,
 3,
 1,
 3,
 5,
 5,
 4,
 6,
 4,
 3,
 5,
 6,
 5,
 3,
 5,
 6,
 5,
 4,
 6,
 5,
 6,
 6,
 2,
 3,
 2,
 3,
 6,
 1,
 3,
 5,
 3,
 6,
 5,
 2,
 3,
 4,
 ...]

In [42]:
accuracy_score(Y_te, y_pred)

0.7721212121212121