In [1]:
import numpy as np
import cv2
import pandas as pd
import glob

In [2]:
andesite_data = []
files = glob.glob ("C:/Users/KIIT/Downloads/geological_similarity/andesite/*.jpg")
for myFile in files:
    image = cv2.imread (myFile)
    andesite_data.append (image)

print('Andesite_data shape:', np.array(andesite_data).shape)

Andesite_data shape: (5000, 28, 28, 3)

In [3]:
gneiss_data = []
files = glob.glob ("C:/Users/KIIT/Downloads/geological_similarity/gneiss/*.jpg")
for myFile in files:
    image = cv2.imread (myFile)
    gneiss_data.append (image)

print('gneiss_data shape:', np.array(gneiss_data).shape)

gneiss_data shape: (5000, 28, 28, 3)

In [4]:
marble_data = []
files = glob.glob ("C:/Users/KIIT/Downloads/geological_similarity/marble/*.jpg")
for myFile in files:
    image = cv2.imread (myFile)
    marble_data.append (image)

print('marble_data shape:', np.array(marble_data).shape)

marble_data shape: (4998, 28, 28, 3)

In [5]:
quartzite_data = []
files = glob.glob ("C:/Users/KIIT/Downloads/geological_similarity/quartzite/*.jpg")
for myFile in files:
    image = cv2.imread (myFile)
    quartzite_data.append (image)

print('marble_data shape:', np.array(quartzite_data).shape)

marble_data shape: (5000, 28, 28, 3)

In [6]:
rhyolite_data = []
files = glob.glob ("C:/Users/KIIT/Downloads/geological_similarity/rhyolite/*.jpg")
for myFile in files:
    image = cv2.imread (myFile)
    rhyolite_data.append (image)

print('rhyolite_data shape:', np.array(rhyolite_data).shape)

rhyolite_data shape: (5000, 28, 28, 3)

In [7]:
schist_data = []
files = glob.glob ("C:/Users/KIIT/Downloads/geological_similarity/rhyolite/*.jpg")
for myFile in files:
    image = cv2.imread (myFile)
    schist_data.append (image)

print('schist_data shape:', np.array(schist_data).shape)

schist_data shape: (5000, 28, 28, 3)

In [8]:
df1 = pd.DataFrame(columns=list(range(2352)))
for i in range(len(schist_data)):
         df1.loc[i]=schist_data[i].flatten()

In [9]:
df2 = pd.DataFrame(columns=list(range(2352)))
for i in range(len(rhyolite_data)):
         df2.loc[i]=rhyolite_data[i].flatten()

In [10]:
df3 = pd.DataFrame(columns=list(range(2352)))
for i in range(len(quartzite_data)):
         df3.loc[i]=quartzite_data[i].flatten()

In [11]:
df4 = pd.DataFrame(columns=list(range(2352)))
for i in range(len(marble_data)):
         df4.loc[i]=marble_data[i].flatten()

In [12]:
df5 = pd.DataFrame(columns=list(range(2352)))
for i in range(len(gneiss_data)):
         df5.loc[i]=gneiss_data[i].flatten()

In [13]:
df6 = pd.DataFrame(columns=list(range(2352)))
for i in range(len(andesite_data)):
         df6.loc[i]=andesite_data[i].flatten()

In [14]:
schist = []
for i in range(5000):
    schist.append('Schist')
df1['Type'] = schist

In [15]:
rhyolite = []
for i in range(5000):
    rhyolite.append('Rhyolite')
df2['Type'] = rhyolite

In [16]:
quartzite = []
for i in range(5000):
    quartzite.append('Quartzite')
df3['Type'] = quartzite

In [17]:
marble = []
for i in range(4998):
    marble.append('Marble')
df4['Type'] = marble

In [18]:
gneiss = []
for i in range(5000):
    gneiss.append('Gneiss')
df5['Type'] = gneiss

In [19]:
andesite = []
for i in range(5000):
    andesite.append('Andesite')
df6['Type'] = andesite

In [22]:
frames = [df1, df2, df3,df4,df5,df6]

df_final = pd.concat(frames)

In [24]:
df_final.reset_index(inplace = True)

In [28]:
df_final.to_csv(r'Geological Image Similarity.csv',index = False)

In [29]:
df= pd.read_csv('Geological Image Similarity.csv')

In [31]:
df.drop(['index'],axis=1)

,Type,0,1,2,3,4,5,6,7,8,...,2342,2343,2344,2345,2346,2347,2348,2349,2350,2351
0,Schist,159,159,153,134,131,126,69,62,59,...,112,132,143,117,113,126,100,72,87,60
1,Schist,55,59,53,53,58,56,62,67,70,...,83,101,110,100,47,54,49,78,85,80
2,Schist,87,86,90,90,87,89,90,85,86,...,62,74,80,69,89,90,80,82,84,72
3,Schist,82,91,94,74,83,86,51,56,59,...,21,46,46,30,118,115,107,140,135,132
4,Schist,136,139,114,124,126,104,97,97,81,...,103,57,51,28,82,79,58,139,140,120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29993,Andesite,59,70,50,71,82,62,68,77,56,...,57,77,76,56,84,80,61,96,92,73
29994,Andesite,119,116,102,118,115,101,125,121,110,...,109,143,137,118,156,152,128,153,149,124
29995,Andesite,114,122,99,119,127,104,116,125,99,...,109,125,127,107,108,110,91,117,119,100
29996,Andesite,133,132,118,138,137,123,139,136,121,...,112,124,117,100,134,126,109,133,125,108
29997,Andesite,170,148,137,145,125,114,137,116,108,...,175,224,203,195,217,195,184,204,182,171

In [32]:
from sklearn.utils import shuffle
df = shuffle(df)

In [33]:
df

,index,Type,0,1,2,3,4,5,6,7,...,2342,2343,2344,2345,2346,2347,2348,2349,2350,2351
28623,3625,Andesite,119,115,96,121,117,98,126,122,...,106,127,125,107,134,132,114,132,130,112
26908,1910,Andesite,131,124,105,131,124,105,128,120,...,117,137,130,115,134,127,112,134,127,112
5968,968,Rhyolite,108,102,89,91,90,76,118,125,...,72,80,78,68,116,118,106,135,142,129
3001,3001,Schist,106,115,95,104,110,91,99,99,...,102,97,106,79,88,97,77,117,125,108
2498,2498,Schist,86,94,87,97,106,96,111,124,...,60,65,73,72,80,85,84,83,88,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18809,3809,Marble,74,79,110,103,116,132,108,137,...,103,26,42,59,34,44,78,30,39,82
23693,3695,Gneiss,101,89,161,116,108,169,139,140,...,218,222,229,222,219,227,216,221,230,217
27805,2807,Andesite,129,118,110,120,109,101,122,113,...,115,128,114,108,126,112,106,126,112,106
1827,1827,Schist,102,105,110,84,87,91,86,85,...,92,98,97,93,91,88,84,92,89,84
927,927,Schist,63,67,56,74,78,67,68,72,...,73,82,86,81,87,91,86,64,68,63

In [34]:
from sklearn.model_selection import train_test_split

In [48]:
X=df.drop(['Type','index'],axis=1)
Y = df['Type']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.33)

In [170]:

from sklearn.ensemble import RandomForestClassifier

In [175]:
model = RandomForestClassifier()
model.fit(X_train, Y_train)  #fit the model

C:\Users\KIIT\AppData\Roaming\Python\Python37\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [176]:
pred = model.predict(X_test)

In [177]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, pred)

0.6841414141414142

# Dealing with Deep Learning

In [70]:
dl_data=np.concatenate((schist_data, rhyolite_data,quartzite_data,marble_data,gneiss_data,andesite_data), axis=0)

In [109]:
dl_data = np.array(dl_data)

### Labeling Data 1-schist , 2- rhyolite , 3-quartzite , 4-marble , 5-gneiss , 6-andesite

In [112]:
label_data = []

In [118]:
for i in range(5000):
    label_data.append(1)
for i in range(5000):
    label_data.append(2)
for i in range(5000):
    label_data.append(3)
for i in range(4998):
    label_data.append(4)
for i in range(5000):
    label_data.append(5)
for i in range(5000):
    label_data.append(6)

In [119]:
len(label_data)

29998

In [120]:
from tensorflow import keras

In [157]:
import random
c = list(zip(dl_data, label_data))

random.shuffle(c)

dl_data, label_data = zip(*c)
X_tr,X_te,Y_tr,Y_te = train_test_split(dl_data,label_data , test_size=0.33)

In [160]:
GeographicalModel = keras.Sequential([
                               keras.layers.Flatten(input_shape = (28,28,3)), # as we have seen our data is in 28,28,3
                               keras.layers.Dense(128,activation='relu'),
                               keras.layers.Dense(10,activation = 'softmax')
])
GeographicalModel.compile(optimizer = 'adam' , loss = 'sparse_categorical_crossentropy' , metrics = ['accuracy'])
GeographicalModel.fit(x=np.array(X_tr), y=np.array(Y_tr),epochs = 10)

Epoch 1/10
629/629 [==============================] - 2s 4ms/step - loss: 27.3001 - accuracy: 0.4910
Epoch 2/10
629/629 [==============================] - 2s 4ms/step - loss: 5.4181 - accuracy: 0.5682
Epoch 3/10
629/629 [==============================] - 3s 4ms/step - loss: 2.4768 - accuracy: 0.5926
Epoch 4/10
629/629 [==============================] - 3s 4ms/step - loss: 1.4975 - accuracy: 0.6242
Epoch 5/10
629/629 [==============================] - 3s 4ms/step - loss: 1.1311 - accuracy: 0.6273
Epoch 6/10
629/629 [==============================] - 3s 4ms/step - loss: 0.8720 - accuracy: 0.6537
Epoch 7/10
629/629 [==============================] - 3s 4ms/step - loss: 0.7498 - accuracy: 0.6715
Epoch 8/10
629/629 [==============================] - 3s 4ms/step - loss: 0.7037 - accuracy: 0.6839
Epoch 9/10
629/629 [==============================] - 3s 4ms/step - loss: 0.7401 - accuracy: 0.6664
Epoch 10/10
629/629 [==============================] - 3s 4ms/step - loss: 0.6602 - accuracy: 0.6983

In [161]:
y_pred = []
for i in range(len(X_te)):
    img = X_te[i]
    img = (np.expand_dims(img,0)) 
    result = GeographicalModel.predict(img) 
    correctResult = np.argmax(result)
    y_pred.append(correctResult)

In [162]:
y_pred

[4,
 5,
 3,
 6,
 4,
 5,
 4,
 4,
 5,
 1,
 6,
 6,
 3,
 4,
 1,
 2,
 1,
 5,
 2,
 3,
 5,
 1,
 4,
 2,
 6,
 6,
 4,
 3,
 6,
 3,
 1,
 6,
 3,
 3,
 1,
 4,
 6,
 1,
 6,
 6,
 1,
 3,
 1,
 1,
 3,
 5,
 5,
 1,
 3,
 3,
 2,
 4,
 3,
 5,
 1,
 4,
 2,
 3,
 5,
 3,
 3,
 1,
 1,
 6,
 6,
 5,
 3,
 1,
 1,
 1,
 4,
 3,
 3,
 1,
 6,
 4,
 3,
 1,
 1,
 1,
 5,
 1,
 6,
 6,
 1,
 4,
 3,
 1,
 1,
 5,
 5,
 6,
 6,
 4,
 1,
 3,
 3,
 2,
 3,
 5,
 4,
 5,
 6,
 3,
 6,
 1,
 5,
 6,
 5,
 1,
 3,
 1,
 3,
 5,
 1,
 3,
 3,
 3,
 5,
 3,
 6,
 4,
 3,
 6,
 6,
 4,
 2,
 3,
 5,
 6,
 3,
 3,
 6,
 6,
 4,
 1,
 3,
 4,
 2,
 2,
 1,
 1,
 2,
 5,
 1,
 3,
 2,
 1,
 1,
 6,
 5,
 3,
 2,
 1,
 1,
 3,
 2,
 3,
 6,
 3,
 4,
 6,
 6,
 3,
 1,
 4,
 1,
 6,
 6,
 4,
 6,
 3,
 1,
 4,
 1,
 3,
 4,
 5,
 1,
 5,
 6,
 4,
 6,
 4,
 5,
 4,
 5,
 6,
 1,
 6,
 3,
 5,
 4,
 5,
 6,
 1,
 4,
 6,
 4,
 1,
 3,
 3,
 1,
 4,
 3,
 6,
 5,
 2,
 4,
 5,
 1,
 3,
 3,
 5,
 1,
 5,
 6,
 4,
 2,
 5,
 2,
 6,
 3,
 2,
 6,
 3,
 4,
 6,
 5,
 6,
 4,
 3,
 1,
 4,
 4,
 5,
 4,
 2,
 5,
 2,
 1,
 5,
 3,
 3,
 2,
 4,
 6,
 1,
 3,
 4,
 5,
 2,
 2,
 1,
 6,
 5,
 5,
 5,
 5,
 3,
 6,
 4,
 6,
 2,
 1,
 5,
 1,
 5,
 6,
 3,
 6,
 1,
 6,
 1,
 4,
 6,
 6,
 5,
 4,
 3,
 1,
 3,
 3,
 1,
 1,
 2,
 2,
 4,
 4,
 4,
 4,
 4,
 6,
 6,
 5,
 4,
 1,
 6,
 6,
 5,
 1,
 1,
 4,
 2,
 3,
 3,
 3,
 4,
 3,
 4,
 1,
 3,
 6,
 1,
 5,
 3,
 1,
 2,
 3,
 3,
 6,
 1,
 6,
 2,
 6,
 6,
 5,
 3,
 6,
 6,
 4,
 5,
 4,
 3,
 4,
 5,
 5,
 4,
 5,
 6,
 3,
 5,
 1,
 2,
 6,
 2,
 2,
 4,
 1,
 4,
 1,
 2,
 1,
 5,
 4,
 1,
 4,
 1,
 6,
 4,
 6,
 1,
 1,
 3,
 6,
 4,
 5,
 5,
 5,
 4,
 3,
 3,
 3,
 6,
 3,
 2,
 1,
 5,
 5,
 2,
 2,
 6,
 4,
 5,
 1,
 5,
 3,
 3,
 5,
 3,
 3,
 4,
 1,
 3,
 2,
 3,
 5,
 5,
 3,
 2,
 6,
 6,
 4,
 4,
 6,
 5,
 3,
 6,
 2,
 4,
 3,
 1,
 2,
 3,
 3,
 4,
 6,
 5,
 5,
 2,
 1,
 4,
 4,
 1,
 3,
 1,
 1,
 6,
 5,
 4,
 5,
 3,
 4,
 5,
 1,
 1,
 6,
 4,
 6,
 5,
 4,
 1,
 5,
 4,
 4,
 3,
 6,
 3,
 1,
 3,
 4,
 4,
 3,
 3,
 6,
 3,
 5,
 3,
 1,
 1,
 4,
 6,
 4,
 1,
 5,
 5,
 3,
 6,
 5,
 4,
 4,
 5,
 1,
 4,
 2,
 6,
 3,
 5,
 3,
 2,
 3,
 3,
 6,
 6,
 3,
 1,
 5,
 2,
 6,
 1,
 4,
 1,
 4,
 2,
 6,
 4,
 1,
 4,
 5,
 2,
 6,
 4,
 5,
 2,
 4,
 3,
 4,
 6,
 6,
 1,
 3,
 5,
 6,
 1,
 5,
 2,
 3,
 5,
 4,
 2,
 2,
 3,
 2,
 6,
 4,
 3,
 2,
 1,
 1,
 3,
 3,
 6,
 5,
 3,
 5,
 4,
 1,
 3,
 3,
 4,
 3,
 5,
 5,
 5,
 3,
 6,
 2,
 5,
 4,
 3,
 1,
 1,
 3,
 1,
 1,
 3,
 3,
 3,
 2,
 1,
 5,
 6,
 3,
 4,
 3,
 3,
 6,
 3,
 3,
 1,
 3,
 6,
 4,
 6,
 5,
 3,
 5,
 1,
 5,
 2,
 4,
 3,
 4,
 2,
 6,
 4,
 3,
 6,
 2,
 3,
 2,
 1,
 4,
 2,
 6,
 6,
 4,
 4,
 3,
 2,
 6,
 6,
 1,
 5,
 1,
 3,
 4,
 1,
 1,
 4,
 6,
 3,
 1,
 4,
 3,
 6,
 4,
 1,
 1,
 3,
 3,
 3,
 5,
 5,
 2,
 5,
 4,
 6,
 6,
 4,
 2,
 1,
 2,
 1,
 2,
 5,
 3,
 6,
 1,
 2,
 2,
 1,
 1,
 5,
 2,
 4,
 2,
 6,
 1,
 4,
 2,
 2,
 1,
 1,
 4,
 3,
 4,
 4,
 4,
 3,
 1,
 6,
 4,
 5,
 6,
 6,
 6,
 5,
 1,
 3,
 6,
 3,
 6,
 2,
 3,
 3,
 5,
 6,
 6,
 5,
 3,
 4,
 4,
 4,
 4,
 6,
 5,
 3,
 6,
 1,
 1,
 1,
 6,
 2,
 5,
 6,
 1,
 6,
 3,
 3,
 3,
 5,
 6,
 3,
 6,
 3,
 4,
 4,
 6,
 3,
 4,
 2,
 1,
 6,
 6,
 6,
 1,
 2,
 4,
 3,
 5,
 4,
 3,
 1,
 1,
 5,
 5,
 3,
 2,
 1,
 5,
 1,
 6,
 2,
 4,
 6,
 6,
 1,
 4,
 5,
 4,
 4,
 5,
 3,
 5,
 4,
 3,
 4,
 3,
 3,
 4,
 3,
 2,
 5,
 1,
 3,
 1,
 1,
 6,
 3,
 5,
 5,
 1,
 6,
 3,
 5,
 2,
 1,
 6,
 2,
 2,
 5,
 6,
 3,
 3,
 3,
 5,
 5,
 5,
 3,
 3,
 3,
 3,
 1,
 6,
 5,
 6,
 5,
 6,
 4,
 5,
 2,
 6,
 5,
 2,
 4,
 3,
 4,
 6,
 1,
 2,
 3,
 3,
 3,
 1,
 1,
 5,
 5,
 4,
 1,
 1,
 3,
 1,
 6,
 1,
 5,
 4,
 3,
 4,
 1,
 5,
 2,
 3,
 5,
 6,
 6,
 2,
 4,
 3,
 3,
 5,
 3,
 6,
 6,
 6,
 1,
 5,
 6,
 4,
 5,
 5,
 4,
 4,
 5,
 6,
 4,
 4,
 5,
 5,
 1,
 5,
 4,
 2,
 2,
 1,
 1,
 1,
 5,
 1,
 4,
 4,
 4,
 1,
 6,
 5,
 1,
 2,
 6,
 1,
 2,
 4,
 3,
 3,
 1,
 1,
 2,
 3,
 1,
 6,
 2,
 6,
 5,
 5,
 4,
 1,
 3,
 3,
 6,
 5,
 1,
 4,
 6,
 2,
 4,
 1,
 5,
 2,
 3,
 5,
 1,
 6,
 6,
 3,
 3,
 3,
 5,
 6,
 3,
 6,
 6,
 5,
 5,
 1,
 3,
 2,
 4,
 3,
 3,
 1,
 3,
 4,
 3,
 5,
 4,
 5,
 6,
 4,
 3,
 6,
 3,
 4,
 4,
 5,
 5,
 3,
 3,
 3,
 6,
 1,
 2,
 5,
 5,
 3,
 5,
 4,
 4,
 1,
 5,
 4,
 2,
 6,
 1,
 6,
 6,
 4,
 4,
 5,
 1,
 5,
 1,
 3,
 5,
 6,
 6,
 3,
 5,
 3,
 4,
 5,
 1,
 5,
 3,
 4,
 3,
 6,
 2,
 1,
 4,
 4,
 6,
 3,
 4,
 5,
 6,
 6,
 5,
 6,
 5,
 1,
 6,
 4,
 4,
 4,
 3,
 1,
 6,
 3,
 5,
 1,
 4,
 ...]

In [165]:
accuracy_score(Y_te, y_pred)

0.7079797979797979